config/routes.rb
Rails.application.routes.draw do
  
  get 'savelist/update'
  get 'savelist/index'

  get 'static_pages/home'
  get 'static_pages/about'
  get 'description/cart'
  get 'description/checkout'
  get '/home', to: 'static_pages#home'
   
   resources :products, only: [:description] do
     resources :description
end 
  
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  post "apply_newsletter", :controller=>"static_pages"
  post "/savelist/update", :controller=>"savelist"
  get "/savelist/banner", :controller=>"savelist"
    resources :categories, only: [:index] do
    resources :products, only: [:index]
     end

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'static_pages#home'


 end

app/controllers/description_controller.rb
class DescriptionController < ApplicationController
    def index
    @product = Product.find(params[:product_id])

end
    def cart
         if current_user    
        @order = Order.find_by(user: current_user)
        @item = OrderItem.where(order: @order)
        
    else
         redirect_to   new_user_session_path
     end
        
        
    end
    
    def checkout
        @order = Order.find_by(user: current_user)
        @item = OrderItem.where(order: @order)
        @item.destroy_all
        @order.destroy
         redirect_to  description_cart_path
            
    end
    
    def create
        if current_user       
        userorder  = Order.where(user: current_user)
    if userorder == []
       userorder = Order.create(user: current_user)
       userorder.save!
    end
     @product = Product.find(params[:product_id])
     price = @product.price*params[:quantity].to_i
     OrderItem.create(quantity: params[:quantity], size: params[:size], colour: params[:colour], order: Order.find_by(user: current_user), price: price, product: @product.title)
    redirect_to  description_cart_path
else
    redirect_to   new_user_session_path
end
end
end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/views/description/cart.html.erb
<h1>Cart</h1> <%=link_to "Checkout",  description_checkout_path %>
<% @item.each do |item| %>
<h3><%=item.product%> (<%=item.quantity%>) Size: <%=item.size%> Colour: <%=item.colour%>  $<%=item.price%></h3> 

<%end%>

app/views/description/index.html.erb
<%= form_with do |form| %>
 <!--https://getbootstrap.com/docs/4.5/components/carousel/ -->
<h1><%=@product.title%> - $<%=@product.price%>         <%= form.submit "Add to cart" %> </h1>
<h3><%=@product.description%></h3> 
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      
      <%= image_tag @product.title + ".jpg", size: "200x200", class: "mx-auto d-block", :alt => @product.title %>
    </div>

    <div class="item">
     <%= image_tag @product.title + ".jpg", size: "200x200", class: "mx-auto d-block", :alt => @product.title %>
    </div>
    

    <div class="item">
    <%= image_tag @product.title + ".jpg", size: "200x200", class: "mx-auto d-block", :alt => @product.title %>
    </div>
  
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h4>Current Rating: <%=@product.rating%>        </h4> 

<label for="colour">Choose a colour:</label>

<select name="colour" id="colour">
  <option value="Red">Red</option>
  <option value="Blue">Blue</option>
  <option value="Orange">Orange</option>
  <option value="Yellow">Yellow</option>
  <option value="Black">Black</option>
  <option value="Green">Green</option>
  <option value="Pink">Pink</option>
</select>
<br>
<label for="size">Choose a size:</label>
<select name="size" id="size">
  <option value="XS">XS</option>
  <option value="S">S</option>
  <option value="M">M</option>
  <option value="L">L</option>
  <option value="XL">XL</option>
  <option value="XXL">XXL</option>
</select>
 <br>
<label for="quantity">Quantity:</label>
  <input type="number" id="quantity" name="quantity" min="1"  value="1">   
<% end %>