config/routes.rb
Rails.application.routes.draw do
  
  get 'savelist/update'
  get 'savelist/index'

  get 'static_pages/home'
  get 'static_pages/about'
  get 'description/cart'
  get 'description/checkout'
  get '/home', to: 'static_pages#home'
   
   resources :products, only: [:description] do
     resources :description
end 
  
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  post "apply_newsletter", :controller=>"static_pages"
  post "/savelist/update", :controller=>"savelist"
  get "/savelist/banner", :controller=>"savelist"
    resources :categories, only: [:index] do
    resources :products, only: [:index]
     end

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'static_pages#home'


 end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @category = Category.find(params[:category_id])
        @products = @category.products.order(:title)
        @savelist_exists = Savelist.where(product: @product, user: current_or_guest_user) == [] ? false : true
    end
    def description

    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<h2>
    <%= link_to "Categories",  categories_path %>/
    <%= @category.title %>/
    Products
</h2>

<ol>
    <% @products.each do |product| %>
    <li>
      <%= image_tag product.title + ".jpg", alt: product.title, id: "product_image" %>
        <%=link_to savelist_text, savelist_update_path(:product_id => product.id), id: 'savelist_link', remote: true %>
      
        <%end%>
    </li>
    
</ol>