config/routes.rb
Rails.application.routes.draw do
  
  get 'savelist/update'
  get 'savelist/index'

  get 'static_pages/home'
  get 'static_pages/about'
  get 'description/cart'
  get 'description/checkout'
  get '/home', to: 'static_pages#home'
   
   resources :products, only: [:description] do
     resources :description
end 
  
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  post "apply_newsletter", :controller=>"static_pages"
  post "/savelist/update", :controller=>"savelist"
  get "/savelist/banner", :controller=>"savelist"
    resources :categories, only: [:index] do
    resources :products, only: [:index]
     end

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'static_pages#home'


 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
     has_many :product_categories
        has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
belongs_to :order
accepts_nested_attributes_for :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/savelist.rb
class Savelist < ApplicationRecord
  has_many :products
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :savelists
  def email_required?
  false
end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :omniauthable, omniauth_providers: %i[twitter]
         
  validates :password, length: { minimum: 8, maximum: 20 }, unless: -> { password.nil? }
   validates :email, format: {with: /\A(.+)@(.+)[.](.+)\z/, message: "format is invalid", unless: -> {email.nil?} }
  
 def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[8, 12]
    user.save!

   end   
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include AuthorizationHelper
  def savelist_text
    return @savelist_exists ? "Remove from save list" : "Add to save list"
  end
  helper_method :savelist_text 
  
  
  
  def hello
    render html: "hello, world!"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
   
   @categories = Category.order(:title)
     end
end

app/controllers/description_controller.rb
class DescriptionController < ApplicationController
    def index
    @product = Product.find(params[:product_id])

end
    def cart
         if current_user    
        @order = Order.find_by(user: current_user)
        @item = OrderItem.where(order: @order)
        
    else
         redirect_to   new_user_session_path
     end
        
        
    end
    
    def checkout
        @order = Order.find_by(user: current_user)
        @item = OrderItem.where(order: @order)
        @item.destroy_all
        @order.destroy
         redirect_to  description_cart_path
            
    end
    
    def create
        if current_user       
        userorder  = Order.where(user: current_user)
    if userorder == []
       userorder = Order.create(user: current_user)
       userorder.save!
    end
     @product = Product.find(params[:product_id])
     price = @product.price*params[:quantity].to_i
     OrderItem.create(quantity: params[:quantity], size: params[:size], colour: params[:colour], order: Order.find_by(user: current_user), price: price, product: @product.title)
    redirect_to  description_cart_path
else
    redirect_to   new_user_session_path
end
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @category = Category.find(params[:category_id])
        @products = @category.products.order(:title)
        @savelist_exists = Savelist.where(product: @product, user: current_or_guest_user) == [] ? false : true
    end
    def description

    end
end

app/controllers/savelist_controller.rb
class SavelistController < ApplicationController
  
  def index
   
   
  end
    
  def banner
    print(params[:product_id])
    savelist  = Savelist.where(product: Product.find(params[:product_id]), user: current_or_guest_user)
    if savelist == []
      Savelist.create(product: Product.find(params[:product_id]), user: current_or_guest_user)
      @savelist_exists = true
    else
    savelist.destroy_all()
     @savelist_exists = false
      
   end
   redirect_to root_path
    end 
  def update
    print(params[:product_id])
    savelist  = Savelist.where(product: Product.find(params[:product_id]), user: current_or_guest_user)
    if savelist == []
      Savelist.create(product: Product.find(params[:product_id]), user: current_or_guest_user)
      @savelist_exists = true
    else
    savelist.destroy_all()
     @savelist_exists = false
    end 
    respond_to do |format|
      format.html {}
      format.js {}
    end
    

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorization_helper.rb
module AuthorizationHelper
# https://www.alexsears.com/article/persisting-guest-users-rails-devise/
  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if cookies.signed[:guest_user_email]
        logging_in
        if Savelist.find_by(user: guest_user)
          Savelist.find_by(user: guest_user).delete
        end
        guest_user.delete
        cookies.delete :guest_user_email
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user
    # Cache the value the first time it's gotten.
    @cached_guest_user ||=
      User.find_by!(email: (cookies.permanent.signed[:guest_user_email] ||= create_guest_user.email))

  # if cookies.signed[:guest_user_email] invalid
  rescue ActiveRecord::RecordNotFound #
    cookies.delete :guest_user_email
    guest_user
  end

  private

  # called (once) when the user logs in, insert any code your application needs
  # to hand off from guest_user to current_user.
  def logging_in
    # put all your processing for transferring
    # from a guest user to a registered user
    # i.e. update votes, update comments, etc.
  end

  # creates guest user by adding a record to the DB
  # with a guest name and email
  def create_guest_user
    u = User.create(:email => "guest_#{Time.now.to_i}#{rand(99)}@example.com")
    u.save!(:validate => false)
    u
  end

end

app/helpers/description_helper.rb
module DescriptionHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/savelist_helper.rb
module SavelistHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_url %></li> 
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "RAD App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", static_pages_about_url %></li>
         <li><%= link_to "Categories", categories_path %></li>
          <li><%= link_to "Save list", savelist_index_path %></li>
          <li><%= link_to "Cart", description_cart_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | RAD App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>